In [29]:
import numpy as np
import scipy.sparse as sp
import pandas as pd

In [8]:
idx_features_labels = np.genfromtxt("./data/cora/cora.content", dtype=np.dtype(str))
print(idx_features_labels, idx_features_labels.shape)

[['31336' '0' '0' ... '0' '0' 'Neural_Networks']
 ['1061127' '0' '0' ... '0' '0' 'Rule_Learning']
 ['1106406' '0' '0' ... '0' '0' 'Reinforcement_Learning']
 ...
 ['1128978' '0' '0' ... '0' '0' 'Genetic_Algorithms']
 ['117328' '0' '0' ... '0' '0' 'Case_Based']
 ['24043' '0' '0' ... '0' '0' 'Neural_Networks']] (2708, 1435)


In [9]:
features = sp.csr_matrix(idx_features_labels[:, 1:-1], dtype=np.float32)
print(features, features.shape)

  (0, 0)	0.0
  (0, 1)	0.0
  (0, 2)	0.0
  (0, 3)	0.0
  (0, 4)	0.0
  (0, 5)	0.0
  (0, 6)	0.0
  (0, 7)	0.0
  (0, 8)	0.0
  (0, 9)	0.0
  (0, 10)	0.0
  (0, 11)	0.0
  (0, 12)	0.0
  (0, 13)	0.0
  (0, 14)	0.0
  (0, 15)	0.0
  (0, 16)	0.0
  (0, 17)	0.0
  (0, 18)	0.0
  (0, 19)	0.0
  (0, 20)	0.0
  (0, 21)	0.0
  (0, 22)	0.0
  (0, 23)	0.0
  (0, 24)	0.0
  :	:
  (2707, 1408)	0.0
  (2707, 1409)	0.0
  (2707, 1410)	0.0
  (2707, 1411)	0.0
  (2707, 1412)	0.0
  (2707, 1413)	0.0
  (2707, 1414)	0.0
  (2707, 1415)	0.0
  (2707, 1416)	0.0
  (2707, 1417)	0.0
  (2707, 1418)	0.0
  (2707, 1419)	0.0
  (2707, 1420)	0.0
  (2707, 1421)	0.0
  (2707, 1422)	0.0
  (2707, 1423)	0.0
  (2707, 1424)	0.0
  (2707, 1425)	0.0
  (2707, 1426)	0.0
  (2707, 1427)	0.0
  (2707, 1428)	0.0
  (2707, 1429)	0.0
  (2707, 1430)	0.0
  (2707, 1431)	0.0
  (2707, 1432)	0.0 (2708, 1433)


In [17]:
print(sp.csr_matrix([['0','0','1'],['0','1','0'],['1','0','0']], dtype=np.float32))

  (0, 0)	0.0
  (0, 1)	0.0
  (0, 2)	1.0
  (1, 0)	0.0
  (1, 1)	1.0
  (1, 2)	0.0
  (2, 0)	1.0
  (2, 1)	0.0
  (2, 2)	0.0


In [30]:
def encode_onehot(labels):
    classes = set(labels)
    classes_dict = {c: np.identity(len(classes))[i, :] for i, c in enumerate(classes)}
    label_onehot = np.array(list(map(classes_dict.get, labels))
                            , dtype=np.int32)
    return label_onehot

In [27]:
labels = encode_onehot(idx_features_labels[:, -1])
print(labels)

[[0 0 0 ... 0 1 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]]


In [37]:
# 或者直接调用
labels_pd = pd.get_dummies(idx_features_labels[:, -1])
print(np.array(labels_pd, dtype=np.int32))

[[0 0 1 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 1 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]]
